### PR TITLE
Upgrade and migrate according to the docs

### PR DESCRIPTION
**Pull request by YoruNoHikage**
Changed a few obsolete stuff explained in the migration docs.
I'm updating my blog so I thought you might want these changes as well. Let's get them pushed back in the main repo. :)

### CODE REVIEW

**Comment by chmac** [comment]
Just spotted this PR today. I've fixed my notification settings!

Thanks for contributing. I'm checking out your PR now and will merge shortly.

**Comment by YoruNoHikage** [comment]
Awesome! :)

**Comment by chmac** [comment]
There was a huge [PR upstream](https://github.com/alxshelepenok/gatsby-starter-lumen/pull/70) which was submitted in May and merged in October. The result is that our v2 fork is no longer merge compatible with upstream. We're submitting this v2 version to the starters list directly.

**Comment by YoruNoHikage** [comment]
Wow, no luck, didn't see that huge refactor...

**Comment by chmac** [comment]
@YoruNoHikage Yeah, it was an unmerged PR for a long time, so even if we'd spotted it, would have been hard to know if it was going to be merged or not...

**Pull request merged**
