### PR TITLE
Bring code and .eslintrc in line

### PR DESCRIPTION
**Pull request by MartinRosenberg**
The .eslintrc rules did not match the style of the code. This change applies the existing rules for one-off cases, and changes the rules to match the code in cases where the code largely deviates from them anyway. In particular, in line with `react/jsx-no-target-blank`, it adds `rel="noopener noreferrer"` [as necessary](https://mathiasbynens.github.io/rel-noopener/).

.eslintrc is also formatted for readability. Of note, each instance of `[0]` is changed to `["off"]` for clarity of purpose.

I am unsure how to handle the ESLint warning `ESLint: Dangerous property 'dangerouslySetInnerHTML' found (react/no-danger)` for the two instances of in `src/components/[Page, Post]TemplateDetails/index.js`.

### CODE REVIEW

**Comment by chmac** [comment]
@MartinRosenberg Awesome, thanks for the PR. We usually favour prettier as it mostly just fixes stuff, and we have our editors setup to auto apply it. It’s also possible to get it to play nicely with eslint, but I’m not super familiar with it. I’ll run your changes on my editor and if it all works, merge it. Sounds like you know more about this stuff than me!

We could use a one-line escape for eslint to create 2 no-danger exceptions.

**Comment by MartinRosenberg** [comment]
@chmac I haven't used prettier before, but from my brief look into it, it seems less configurable than ESLint. It also seems like it would take more effort to get the `.prettierrc` in line. But to be completely honest, I'm actually new to all of this, and almost certainly don't know more than you. Seeing as you'll be the primary maintainer of the starter, I defer to your preferences.

**Comment by chmac** [comment]
@MartinRosenberg Finally got this loaded onto my laptop. When I run `yarn format` I get one small change to `gatsby-config.js`. When I then run `yarn lint` I get an error about that change.

I've made a couple of changes on top of your branch:

* Added `prettier` to the list of eslint "extends"
* Applied `yarn format` (which runs prettier) to the code

~There's still an error on `function-paren-newline`. I guess it's a clash between prettier's settings and airbnb's.~ Scratch that, found a solution. Thanks for kicking this off @MartinRosenberg, seems like now we have almost total linting pass!

**Comment by chmac** [comment]
Haha, I just killed the last 2 linting errors by disabling that rule for those two lines only. Linting is now 100% passing! :-)

**Comment by MartinRosenberg** [comment]
Glad you got that working, and happy to help. May my next contribution be more substantial!

**Pull request merged**
